edb\_exception
==============

.. currentmodule:: pyaedt.edb

.. automethod:: Edb.edb_exception